---

- name: basic setup for all hosts
  hosts: all,!hetzner_storageboxes,!rsync_net
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: unbound }
    # reconfiguring sshd may break the AUR on luna (unchecked)
    #- { role: sshd, tags: ['sshd'] }
    - { role: root_ssh }
    - { role: borg-client, tags: ["borg"], when: "'borg_clients' in group_names" }
    - { role: zabbix-agent, tags: ["zabbix"], when: "'unmanaged' not in group_names" }
    - { role: hardening }
